language: erlang
otp_release:
  - 20.0
  - 20.1.3
  - 21.2

services:
  - docker

cache:
  directories:
    - _build

before_script:
  - git clone https://github.com/erlang/rebar3.git; cd rebar3; ./bootstrap; sudo mv rebar3 /usr/local/bin/; cd -
  - git clone https://github.com/inaka/elvis
  - cd elvis
  - rebar3 escriptize
  - sudo cp -r _build/default/bin/elvis /usr/local/bin
  - cd -
  - rebar3 compile
  - make start-redis

script:
  - make test
